import arrizo6 from "../src/assets/images/arrizo-6.webp";
import benzE280 from "../src/assets/images/benz-e280.png";
import cherryArizo from "../src/assets/images/cherry-arizo.png";
import dena from "../src/assets/images/dena.webp";
import elentra from "../src/assets/images/elentra.png";
import fownix from "../src/assets/images/fownix.webp";
import hyundaiSantafe from "../src/assets/images/hyundai-santafe.png";
import hyundaiSonata from "../src/assets/images/hyundai-sonata.png";
import jacg7 from "../src/assets/images/jacg7.webp";
import kiaCerato from "../src/assets/images/kia-cerato-.png";
import kiaSorento from "../src/assets/images/kia-sorento.png";
import l90 from "../src/assets/images/l90.png";
import lanser from "../src/assets/images/lanser.png";
import mvmNew from "../src/assets/images/mvm-new.webp";
import mvmX33 from "../src/assets/images/mvm-x33.webp";
import optima from "../src/assets/images/optima.png";
import p206 from "../src/assets/images/p206.png";
import p207Auto from "../src/assets/images/p207-auto.png";
import p207 from "../src/assets/images/p207.png";
import pars from "../src/assets/images/pars.png";
import prado2012 from "../src/assets/images/prado-2012.webp";
import rentalKiaMohavi from "../src/assets/images/rental-kia-mohavi.png";
import samandLx from "../src/assets/images/samand-lx.png";
import shahin from "../src/assets/images/shahin.png";
import sonatalf from "../src/assets/images/sonatalf.webp";
import sportage from "../src/assets/images/sportage.png";
import toyotaPrado from "../src/assets/images/toyota-prado.png";
import tusan from "../src/assets/images/tusan.png";
import vijeTiggo7 from "../src/assets/images/vije-tiggo-7.webp";

export default [
  {
    id: 1,
    Make: "چری",
    Model: "آریزو ۶",
    Year: "۱۴۰۳",
    Color: "مشکی",
    Fuel: "بنزین",
    Transmission: "اتوماتیک",
    Seat: 5,
    Rental: 280000,
    Availability: true,
    Features: ["کولر", "بلوتوث"],
    Location: "تهران",
    image: arrizo6,
  },
  {
    id: 2,
    Make: "مرسدس بنز",
    Model: "E280",
    Year: "۱۴۰۲",
    Color: "نقره‌ای",
    Fuel: "بنزین",
    Transmission: "اتوماتیک",
    Seat: 5,
    Rental: 350000,
    Availability: true,
    Features: ["صندلی چرمی", "سانروف"],
    Location: "تهران",
    image: benzE280,
  },
  {
    id: 3,
    Make: "چری",
    Model: "آریزو",
    Year: "۱۴۰۴",
    Color: "قرمز",
    Fuel: "بنزین",
    Transmission: "اتوماتیک",
    Seat: 5,
    Rental: 300000,
    Availability: true,
    Features: ["کولر", "بلوتوث"],
    Location: "اصفهان",
    image: cherryArizo,
  },
  {
    id: 4,
    Make: "ایران‌خودرو",
    Model: "دنا",
    Year: "۱۴۰۰",
    Color: "سفید",
    Fuel: "بنزین",
    Transmission: "دستی",
    Seat: 5,
    Rental: 220000,
    Availability: true,
    Features: ["کولر", "رادیو"],
    Location: "تهران",
    image: dena,
  },
  {
    id: 5,
    Make: "هیوندای",
    Model: "النترا",
    Year: "۱۴۰۱",
    Color: "سیاه",
    Fuel: "بنزین",
    Transmission: "اتوماتیک",
    Seat: 5,
    Rental: 300000,
    Availability: true,
    Features: ["کولر", "صندلی چرمی", "بلوتوث"],
    Location: "اصفهان",
    image: elentra,
  },
  {
    id: 6,
    Make: "فونیکس",
    Model: "Fownix",
    Year: "۱۴۰۳",
    Color: "نارنجی",
    Fuel: "بنزین",
    Transmission: "دستی",
    Seat: 4,
    Rental: 250000,
    Availability: true,
    Features: ["کولر", "رادیو"],
    Location: "تهران",
    image: fownix,
  },
  {
    id: 7,
    Make: "هیوندای",
    Model: "سانتافه",
    Year: "۱۴۰۰",
    Color: "نقره‌ای",
    Fuel: "بنزین",
    Transmission: "اتوماتیک",
    Seat: 7,
    Rental: 400000,
    Availability: true,
    Features: ["کولر", "سانروف", "دوربین عقب"],
    Location: "تهران",
    image: hyundaiSantafe,
  },
  {
    id: 8,
    Make: "هیوندای",
    Model: "سوناتا",
    Year: "۱۳۹۸",
    Color: "سفید",
    Fuel: "بنزین",
    Transmission: "اتوماتیک",
    Seat: 5,
    Rental: 320000,
    Availability: true,
    Features: ["کولر", "صندلی چرمی", "بلوتوث"],
    Location: "تهران",
    image: hyundaiSonata,
  },
  {
    id: 9,
    Make: "جک",
    Model: "G7",
    Year: "۱۴۰۲",
    Color: "نقره‌ای",
    Fuel: "بنزین",
    Transmission: "اتوماتیک",
    Seat: 5,
    Rental: 300000,
    Availability: true,
    Features: ["کولر", "صندلی چرمی", "سانروف"],
    Location: "تهران",
    image: jacg7,
  },
  {
    id: 10,
    Make: "کیا",
    Model: "سراتو",
    Year: "۱۴۰۰",
    Color: "آبی",
    Fuel: "بنزین",
    Transmission: "اتوماتیک",
    Seat: 5,
    Rental: 290000,
    Availability: true,
    Features: ["کولر", "بلوتوث", "رادار عقب"],
    Location: "اصفهان",
    image: kiaCerato,
  },
  {
    id: 23,
    Make: "پژو",
    Model: "۲۰۶",
    Year: "۱۳۹۷",
    Color: "نقره‌ای",
    Fuel: "بنزین",
    Transmission: "دستی",
    Seat: 5,
    Rental: 200000,
    Availability: true,
    Features: ["کولر", "رادیو"],
    Location: "تهران",
    image: p206,
  },
  {
    id: 22,
    Make: "پژو",
    Model: "۲۰۷ اتوماتیک",
    Year: "۱۳۹۷",
    Color: "نقره‌ای",
    Fuel: "بنزین",
    Transmission: "اتوماتیک",
    Seat: 5,
    Rental: 200000,
    Availability: true,
    Features: ["کولر", "رادیو"],
    Location: "تهران",
    image: p207Auto,
  },
  {
    id: 21,
    Make: "پژو",
    Model: "۲۰۶",
    Year: "۱۳۹۷",
    Color: "سفید",
    Fuel: "بنزین",
    Transmission: "دستی",
    Seat: 5,
    Rental: 200000,
    Availability: true,
    Features: ["کولر", "رادیو"],
    Location: "شیراز",
    image: p207,
  },
  {
    id: 12,
    Make: "پارس",
    Model: "۱۲۰۰",
    Year: "۱۳۹۰",
    Color: "سفید",
    Fuel: "بنزین",
    Transmission: "دستی",
    Seat: 4,
    Rental: 200000,
    Availability: true,
    Features: ["کولر", "رادیو"],
    Location: "تهران",
    image: pars,
  },
  {
    id: 13,
    Make: "تویوتا",
    Model: "پرادو",
    Year: "۱۳۹۱",
    Color: "سیاه",
    Fuel: "بنزین",
    Transmission: "اتوماتیک",
    Seat: 7,
    Rental: 450000,
    Availability: true,
    Features: ["کولر", "صندلی چرمی", "دوربین عقب"],
    Location: "تهران",
    image: prado2012,
  },
  {
    id: 14,
    Make: "کیا",
    Model: "موهاوی",
    Year: "۱۴۰۰",
    Color: "نقره‌ای",
    Fuel: "بنزین",
    Transmission: "اتوماتیک",
    Seat: 7,
    Rental: 380000,
    Availability: true,
    Features: ["کولر", "صندلی چرمی", "سانروف"],
    Location: "تهران",
    image: rentalKiaMohavi,
  },
  {
    id: 15,
    Make: "ایران‌خودرو",
    Model: "سمند LX",
    Year: "۱۳۹۹",
    Color: "نقره‌ای",
    Fuel: "بنزین",
    Transmission: "دستی",
    Seat: 5,
    Rental: 180000,
    Availability: true,
    Features: ["کولر", "رادیو"],
    Location: "تهران",
    image: samandLx,
  },
  {
    id: 16,
    Make: "ایران‌خودرو",
    Model: "شاهین",
    Year: "۱۳۸۰",
    Color: "سفید",
    Fuel: "بنزین",
    Transmission: "دستی",
    Seat: 5,
    Rental: 150000,
    Availability: true,
    Features: ["کولر", "رادیو"],
    Location: "تهران",
    image: shahin,
  },
  {
    id: 17,
    Make: "هیوندای",
    Model: "سوناتا LF",
    Year: "۱۴۰۰",
    Color: "آبی",
    Fuel: "بنزین",
    Transmission: "اتوماتیک",
    Seat: 5,
    Rental: 250000,
    Availability: true,
    Features: ["کولر", "بلوتوث"],
    Location: "تهران",
    image: sonatalf,
  },
  {
    id: 18,
    Make: "کیا",
    Model: "اسپورتیج",
    Year: "۱۴۰۱",
    Color: "سفید",
    Fuel: "بنزین",
    Transmission: "اتوماتیک",
    Seat: 5,
    Rental: 300000,
    Availability: true,
    Features: ["کولر", "سانروف"],
    Location: "تهران",
    image: sportage,
  },
  {
    id: 19,
    Make: "تویوتا",
    Model: "پرادو",
    Year: "۱۴۰۲",
    Color: "مشکی",
    Fuel: "بنزین",
    Transmission: "اتوماتیک",
    Seat: 7,
    Rental: 450000,
    Availability: true,
    Features: ["کولر", "صندلی چرمی", "دوربین عقب"],
    Location: "تهران",
    image: toyotaPrado,
  },
  {
    id: 20,
    Make: "هیوندای",
    Model: "توسان",
    Year: "۱۴۰۰",
    Color: "نقره‌ای",
    Fuel: "بنزین",
    Transmission: "اتوماتیک",
    Seat: 5,
    Rental: 280000,
    Availability: true,
    Features: ["کولر", "بلوتوث", "دوربین عقب"],
    Location: "تهران",
    image: tusan,
  },

  //   id: 1,
  //   Make: "تویوتا",
  //   Model: "کرولا",
  //   Year: "1399",
  //   Color: "سفید",
  //   Fuel: "بنزین",
  //   Transmission: "اتوماتیک",
  //   Seat: 5,
  //   Rental: 250000,
  //   Availability: true,
  //   Features: ["کولر", "رادیو"],
  //   Location: "تهران",
  //   image: tusan,
  // },
  // {
  //   id: 2,
  //   Make: "هیوندای",
  //   Model: "سوناتا",
  //   Year: "1398",
  //   Color: "مشکی",
  //   Fuel: "بنزین",
  //   Transmission: "اتوماتیک",
  //   Seat: 5,
  //   Rental: 280000,
  //   Availability: true,
  //   Features: ["کولر", "بلوتوث"],
  //   Location: "اصفهان",
  //   image: img,
  // },
  //
  // {
  //   id: 4,
  //   Make: "سایپا",
  //   Model: "پراید",
  //   Year: "۱۳۹۵",
  //   Color: "آبی",
  //   Fuel: "گازوئیل",
  //   Transmission: "دستی",
  //   Seat: 5,
  //   Rental: 180000,
  //   Availability: true,
  //   Features: ["کولر"],
  //   Location: "شیراز",
  //   image: img,
  // },
  // {
  //   id: 5,
  //   Make: "بنز",
  //   Model: "E200",
  //   Year: "۱۴۰۰",
  //   Color: "سفید",
  //   Fuel: "بنزین",
  //   Transmission: "اتوماتیک",
  //   Seat: 5,
  //   Rental: 400000,
  //   Availability: true,
  //   Features: ["کولر", "صندلی چرمی", "سانروف"],
  //   Location: "تهران",
  //   image: img,
  // },
  // {
  //   id: 6,
  //   Make: "رنو",
  //   Model: "ساندرو",
  //   Year: "۱۳۹۸",
  //   Color: "سبز",
  //   Fuel: "بنزین",
  //   Transmission: "دستی",
  //   Seat: 4,
  //   Rental: 220000,
  //   Availability: true,
  //   Features: ["کولر", "رادیو"],
  //   Location: "شیراز",
  //   image: img,
  // },
  // {
  //   id: 7,
  //   Make: "پژو",
  //   Model: "۴۰۵",
  //   Year: "۱۳۹۶",
  //   Color: "سفید",
  //   Fuel: "بنزین",
  //   Transmission: "اتوماتیک",
  //   Seat: 5,
  //   Rental: 190000,
  //   Availability: true,
  //   Features: ["کولر", "رادیو"],
  //   Location: "اصفهان",
  //   image: img,
  // },
  // {
  //   id: 8,
  //   Make: "هیوندای",
  //   Model: "توسان",
  //   Year: "۱۴۰۱",
  //   Color: "نقره‌ای",
  //   Fuel: "بنزین",
  //   Transmission: "اتوماتیک",
  //   Seat: 5,
  //   Rental: 320000,
  //   Availability: true,
  //   Features: ["کولر", "بلوتوث", "دوربین عقب"],
  //   Location: "تهران",
  //   image: img,
  // },
  // {
  //   id: 9,
  //   Make: "تویوتا",
  //   Model: "پریوس",
  //   Year: "۱۴۰۰",
  //   Color: "سفید",
  //   Fuel: "هیبرید",
  //   Transmission: "اتوماتیک",
  //   Seat: 5,
  //   Rental: 350000,
  //   Availability: true,
  //   Features: ["کولر", "بلوتوث", "صندلی چرمی"],
  //   Location: "تهران",
  //   image: img,
  // },
  // {
  //   id: 10,
  //   Make: "ایران‌خودرو",
  //   Model: "سمند",
  //   Year: "۱۳۹۴",
  //   Color: "قرمز",
  //   Fuel: "بنزین",
  //   Transmission: "دستی",
  //   Seat: 5,
  //   Rental: 170000,
  //   Availability: true,
  //   Features: ["کولر", "رادیو"],
  //   Location: "اصفهان",
  //   image: img,
  // },
];
