import img from "../src/assets/images/fownix.webp";

export default [
  {
    id: 1,
    Make: "تویوتا",
    Model: "کرولا",
    Year: "1399",
    Color: "سفید",
    Fuel: "بنزین",
    Transmission: "اتوماتیک",
    Seat: 5,
    Rental: 250000,
    Availability: true,
    Features: ["کولر", "رادیو"],
    Location: "تهران",
    image: img,
  },
  {
    id: 2,
    Make: "هیوندای",
    Model: "سوناتا",
    Year: "1398",
    Color: "مشکی",
    Fuel: "بنزین",
    Transmission: "اتوماتیک",
    Seat: 5,
    Rental: 280000,
    Availability: true,
    Features: ["کولر", "بلوتوث"],
    Location: "اصفهان",
    image: img,
  },
  {
    id: 3,
    Make: "پژو",
    Model: "۲۰۶",
    Year: "۱۳۹۷",
    Color: "نقره‌ای",
    Fuel: "بنزین",
    Transmission: "دستی",
    Seat: 5,
    Rental: 200000,
    Availability: true,
    Features: ["کولر", "رادیو"],
    Location: "تهران",
    image: img,
  },
  {
    id: 4,
    Make: "سایپا",
    Model: "پراید",
    Year: "۱۳۹۵",
    Color: "آبی",
    Fuel: "گازوئیل",
    Transmission: "دستی",
    Seat: 5,
    Rental: 180000,
    Availability: true,
    Features: ["کولر"],
    Location: "شیراز",
    image: img,
  },
  {
    id: 5,
    Make: "بنز",
    Model: "E200",
    Year: "۱۴۰۰",
    Color: "سفید",
    Fuel: "بنزین",
    Transmission: "اتوماتیک",
    Seat: 5,
    Rental: 400000,
    Availability: true,
    Features: ["کولر", "صندلی چرمی", "سانروف"],
    Location: "تهران",
    image: img,
  },
  {
    id: 6,
    Make: "رنو",
    Model: "ساندرو",
    Year: "۱۳۹۸",
    Color: "سبز",
    Fuel: "بنزین",
    Transmission: "دستی",
    Seat: 4,
    Rental: 220000,
    Availability: true,
    Features: ["کولر", "رادیو"],
    Location: "شیراز",
    image: img,
  },
  {
    id: 7,
    Make: "پژو",
    Model: "۴۰۵",
    Year: "۱۳۹۶",
    Color: "سفید",
    Fuel: "بنزین",
    Transmission: "اتوماتیک",
    Seat: 5,
    Rental: 190000,
    Availability: true,
    Features: ["کولر", "رادیو"],
    Location: "اصفهان",
    image: img,
  },
  {
    id: 8,
    Make: "هیوندای",
    Model: "توسان",
    Year: "۱۴۰۱",
    Color: "نقره‌ای",
    Fuel: "بنزین",
    Transmission: "اتوماتیک",
    Seat: 5,
    Rental: 320000,
    Availability: true,
    Features: ["کولر", "بلوتوث", "دوربین عقب"],
    Location: "تهران",
    image: img,
  },
  {
    id: 9,
    Make: "تویوتا",
    Model: "پریوس",
    Year: "۱۴۰۰",
    Color: "سفید",
    Fuel: "هیبرید",
    Transmission: "اتوماتیک",
    Seat: 5,
    Rental: 350000,
    Availability: true,
    Features: ["کولر", "بلوتوث", "صندلی چرمی"],
    Location: "تهران",
    image: img,
  },
  {
    id: 10,
    Make: "ایران‌خودرو",
    Model: "سمند",
    Year: "۱۳۹۴",
    Color: "قرمز",
    Fuel: "بنزین",
    Transmission: "دستی",
    Seat: 5,
    Rental: 170000,
    Availability: true,
    Features: ["کولر", "رادیو"],
    Location: "اصفهان",
    image: img,
  },
];
